services:
  build:
    build: .
    volumes:
      - .:/site
    command: haunt build

  serve:
    build: .
    volumes:
      - .:/site
    ports:
      - "8080:8080"
    command: haunt serve -b 0.0.0.0 -p 8080
